# Generated by Django 5.2.1 on 2025-06-05 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="guest_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_email",
            field=models.EmailField(default="guest@example.com", max_length=254),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_name",
            field=models.CharField(default="Guest", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_phone",
            field=models.CharField(default="0000000000", max_length=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
