# Generated by Django 5.2.1 on 2025-06-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_order_guest_email_order_shipping_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="city",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="first_name",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AddField(
            model_name="order",
            name="last_name",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AddField(
            model_name="order",
            name="zip_code",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="primary_image",
            field=models.URLField(default=""),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=models.TextField(default=""),
        ),
    ]
