# Generated by Django 5.2.1 on 2025-06-15 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_order_city_order_first_name_order_last_name_and_more"),
    ]

    operations = [
        # Use raw SQL to remove OAuth columns
        migrations.RunSQL(
            # Forward SQL - Remove OAuth columns
            """
            ALTER TABLE users_user DROP COLUMN IF EXISTS avatar_url;
            ALTER TABLE users_user DROP COLUMN IF EXISTS email_verified;
            ALTER TABLE users_user DROP COLUMN IF EXISTS is_oauth_user;
            
            ALTER TABLE users_socialaccount DROP COLUMN IF EXISTS access_token;
            ALTER TABLE users_socialaccount DROP COLUMN IF EXISTS expires_at;
            ALTER TABLE users_socialaccount DROP COLUMN IF EXISTS provider_avatar;
            ALTER TABLE users_socialaccount DROP COLUMN IF EXISTS provider_email;
            ALTER TABLE users_socialaccount DROP COLUMN IF EXISTS provider_name;
            ALTER TABLE users_socialaccount DROP COLUMN IF EXISTS refresh_token;
            
            ALTER TABLE users_socialaccount RENAME COLUMN provider_id TO uid;
            
            DROP INDEX IF EXISTS users_socialaccount_provider_provider_id_key;
            """,
            # Reverse SQL - Add OAuth columns back (in case we need to rollback)
            """
            ALTER TABLE users_user ADD COLUMN avatar_url VARCHAR(200);
            ALTER TABLE users_user ADD COLUMN email_verified BOOLEAN DEFAULT FALSE;
            ALTER TABLE users_user ADD COLUMN is_oauth_user BOOLEAN DEFAULT FALSE;
            
            ALTER TABLE users_socialaccount ADD COLUMN access_token TEXT;
            ALTER TABLE users_socialaccount ADD COLUMN expires_at TIMESTAMP;
            ALTER TABLE users_socialaccount ADD COLUMN provider_avatar VARCHAR(200);
            ALTER TABLE users_socialaccount ADD COLUMN provider_email VARCHAR(254);
            ALTER TABLE users_socialaccount ADD COLUMN provider_name VARCHAR(255);
            ALTER TABLE users_socialaccount ADD COLUMN refresh_token TEXT;
            
            ALTER TABLE users_socialaccount RENAME COLUMN uid TO provider_id;
            
            CREATE UNIQUE INDEX users_socialaccount_provider_provider_id_key 
            ON users_socialaccount (provider, provider_id);
            """
        ),
    ]
