# Generated by Django 5.2.1 on 2025-05-30 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="parent_category",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="items.category",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("name", "parent_category")},
        ),
    ]
