# Generated by Django 5.2.1 on 2025-05-30 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_category_parent_category_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="category",
            table="categories",
        ),
        migrations.AlterModelTable(
            name="item",
            table="items",
        ),
        migrations.AlterModelTable(
            name="itemdetail",
            table="details",
        ),
        migrations.AlterModelTable(
            name="itemimage",
            table="images",
        ),
        migrations.AlterModelTable(
            name="itemsize",
            table="sizes",
        ),
    ]
