# Generated by Django 5.2.1 on 2025-05-30 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_insert_initial_data"),
        ("items", "0003_alter_category_table_alter_item_table_and_more"),
    ]

    operations = []
