# Generated by Django 5.2.1 on 2025-05-31 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0008_remove_high_quality_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemimage",
            name="quality",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium")], max_length=10
            ),
        ),
        migrations.CreateModel(
            name="DetailImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image_url", models.URLField(max_length=255)),
                ("display_order", models.IntegerField(default=0)),
                (
                    "item",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detail_images",
                        to="items.item",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Detail Images",
                "db_table": "detail_images",
                "ordering": ["display_order"],
            },
        ),
    ]
